### ISSUE TITLE
Problem with ground plane

### ISSUE THREAD

**Issue by smooker** [tlantela/KiCAD_layout_cloner#1]
Iterating through all the pads for each cloned zone, might take a few seconds...
Original zone location (243110000, 148500000) ###bottom right of the ground planes areas
Traceback (most recent call last):
  File "./layout_cloner.py", line 110, in <module>
    if templateRect.Contains(zone.GetPosition()) and zone.GetLayer() is not 41:     #If the zone is inside the area to be cloned (the comment zone) and it is not the comment zone (layer 41)
NameError: name 'templateRect' is not defined

**Comment by mihnen** [comment]
Same issue here:

Original reference:  U201 , Generated clone references []
Original reference:  C201 , Generated clone references []
Original reference:  R201 , Generated clone references []
Original reference:  R202 , Generated clone references []
Original reference:  R203 , Generated clone references []
Original reference:  C202 , Generated clone references []
Original reference:  U202 , Generated clone references []
Original reference:  U203 , Generated clone references []
Original reference:  U204 , Generated clone references []
Original reference:  R204 , Generated clone references []
Original reference:  R205 , Generated clone references []
Original reference:  R206 , Generated clone references []
Original reference:  P201 , Generated clone references []
Modules moved and oriented according to template.
Iterating through all the pads for each cloned zone, might take a few seconds...
Zones cloned.
Traceback (most recent call last):
  File "layout_cloner.py", line 121, in <module>
    if track.HitTest(templateRect):                                                     #Find tracks which touch the comment zone
NameError: name 'templateRect' is not defined

**Comment by tlantela** [comment]
Sorry, I don't really maintain the code or offer support as you may have noticed from the couple of years of delay in responding... Feel free to fix any bugs you encounter and commit.
